name: Core BotBlitz Validations

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install protoc
      run: sudo apt-get install -y protobuf-compiler

    - name: Clean generated proto
      run: make clean

    - name: Generate proto
      run: make gen

    - name: Test Monorepo
      run: make test
