# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "fix-settle-bets-workflow" ]
  schedule:
    # 4PM (PT) daily
    - cron:  '0 23 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB: nba-bets/nbastat.db # DB location
      DISCORD_WEBHOOK: https://discord.com/api/webhooks/1203794391362437242/9kOW437LYjip9F_FCUu30_-DnuZhqpY1t5TtnSCNtPTKw6KZRYG18dvM8KAvlH0rBohu
      ODDS_API_KEY: a23c9884795b77de65081cc5fa65b8ff
    steps:
    - uses: actions/checkout@v2
      with:
        ref: fix-settle-bets-workflow
    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        args: --exit-node=raspberrypi
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f nba-bets/requirements.txt ]; then pip install -r nba-bets/requirements.txt; fi
    - name: Download Database
      run: python nba-bets/download-game-logs.py
    - name: Settle Past Bets
      run: python nba-bets/settle-bets.py
    - name: Download New Bet
      run: python nba-bets/download-bet.py
    - uses: stefanzweifel/git-auto-commit-action@v5
