name: Download Stats and Projections

on:
  # schedule:
  #   - cron: '0 8 * * *'  # Runs every day at 8am UTC
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  download_stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure your dependencies are listed here
          
      - name: Install blitz_env from .whl file
        run: |
          # Install the package from the .whl file
          pip install dist/blitz_env-0.1.0-py3-none-any.whl
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # or your default region

      - name: Remove local blitz_env package directory
        run: |
          rm -rf blitz_env  # Remove the local package directory to avoid conflicts
    
      - name: Calculate current week and run scripts
        run: |
          # Calculate the difference in seconds from September 5, 2024, 8 AM UTC
          PAST_DATE=$(date -d '2024-09-05 08:00:00 UTC' +%s)
          NOW=$(date +%s)
          
          # Calculate the number of weeks since the past date using integer division
          SECONDS_IN_A_WEEK=$((7 * 24 * 60 * 60))
          DIFF=$((NOW - PAST_DATE))
          CURRENT_WEEK=$(( DIFF / SECONDS_IN_A_WEEK + 1 ))
          
          # Print out what will be run (just for logging)
          echo "Running stats download for week range: $CURRENT_WEEK"

          # Run the python scripts with the calculated week range
          python -m blitz_env.download_stats --year 2024 --week $CURRENT_WEEK -o s3://botblitz/stats
          python -m blitz_env.download_projections --year 2024 --week $CURRENT_WEEK -o s3://botblitz/projections

      - name: Show output (optional)
        run: |
          echo "Week Range: $WEEK_RANGE"
          echo "Stats and projections have been downloaded to S3."
