name: BotBlitz Weekly Fantasy

on:
  workflow_dispatch:
  schedule:
     - cron: "47 15 * * 3"

jobs:
  buildAndTest:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
  
    - uses: actions/setup-go@v5.0.0
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.
        go-version: '1.21.7'
    
    - name: Check starting Go version
      run: go version

    - name: Install protoc
      run: sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y protobuf-compiler

    - name: Install golang proto tools
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

    - name: Install GRPC proto tools
      run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Install python grpc tools
      run: pip install -r requirements.txt

    - name: Check protoc version
      run: protoc --version

    - name: Docker version
      run: docker -v

    - name: Clean generated proto
      run: make clean

    - name: Generate proto
      run: make gen

    - name: Test Monorepo
      run: make test
    
    - name: Build python module
      run: make build-py-module

    - name: Build docker image
      run: make build-docker

    - name: Run Weekly Fantasy
      run: make run-weekly-fantasy-github
      env:
          RYAN_ENV: ${{ secrets.RYAN_ENV }}
          TYLER_ENV: ${{ secrets.TYLER_ENV }}
          PHILIP_ENV: ${{ secrets.PHILIP_ENV }}

    # - name: Create PR w/ new gamestate
    #   id: cpr
    #   uses: peter-evans/create-pull-request@v7
    #   with:
    #     token: ${{ github.token }}
    #     title: '[Automated] Weekly Fantasy GameState Update'
    #     commit-message: '[Automated] Weekly Fantasy GameState Update'
    #     sign-commits: true
    #     add-paths: |
    #         data/game_states/*.bin
    #     body-path: '/tmp/weekly_transaction_log.txt'

    # - name: Enable Pull Request Automerge
    #   if: steps.cpr.outputs.pull-request-operation == 'created'
    #   uses: peter-evans/enable-pull-request-automerge@v3
    #   with:
    #     token: ${{ github.token }}
    #     pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}

    # - name: Run Engine
    #   run: make run-engine
